POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "johndoe14@example.com",
  "password": "securePassword123"
}


# POST http://localhost:3000/api/auth/register
# Content-Type: application/json

# {
#   "fullName": {
#     "firstName": "John",
#     "lastName": "Doe"
#   },
#   "email": "johndoe14@example.com",
#   "password": "securePassword123"
# }