

POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "fullName": {
    "firstName": "John",
    "lastName": "Doe"
  },
  "email": "johndoe15@example.com",
  "password": "securePassword123"
}